apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    selector:
        app: backend
    type: NodePort
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          nodePort: 30008
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend 
                  image: maverick0809/todob
                #   resources:
                #       limits:
                #           cpu: '500m'
                #           memory: '512Mi'
                #       requests:
                #           cpu: '250m'
                #           memory: '256Mi'

