Vagrant.configure("2") do |config| 
 
    config.vm.define "rancher" do |rancher|
        rancher.vm.box = "ubuntu/bionic64"
        rancher.vm.network "private_network", ip: "192.168.33.41"
	rancher.vm.network "private_network", ip: "10.0.0.41"
        rancher.vm.network "public_network"
        rancher.vm.provider "virtualbox" do |vb|
	  vb.name = "RANCHER"
          vb.memory = "2024"
          vb.cpus = 2
      end 
    end

end