apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: fluent-bit
    namespace: logging
    labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: 'true' #? not formal, it's custom
spec:
    selector:
        matchLabels:
            k8s-app: fluent-bit-logging
    template:
        metadata:
            labels:
                k8s-app: fluent-bit-logging
                version: v1
                kubernetes.io/cluster-service: 'true'
            annotations:
                prometheus.io/scrape: 'true'
                prometheus.io/port: '2020'
                prometheus.io/path: /api/v1/metrics/prometheus
        spec:
            terminationGracePeriodSeconds: 10
            containers:
                - name: fluent-bit
                  image: fluent/fluent-bit:1.7.2
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 2020 #? default
                  env:
                      - name: FLUENT_ELASTICSEARCH_HOST
                        value: 'elasticsearch' #? YOUR ELASTICSEARCH IP, here service of elasticsearch
                      - name: FLUENT_ELASTICSEARCH_PORT
                        value: '9200'
                  volumeMounts:
                      - name: varlog
                        mountPath: /var/log
                      - name: varlibdockercontainers
                        mountPath: /var/lib/docker/containers
                        readOnly: true
                      - name: fluent-bit-config
                        mountPath: /fluent-bit/etc/
            volumes:
                - name: varlog
                  hostPath:
                      path: /var/log
                - name: varlibdockercontainers
                  hostPath:
                      path: /var/lib/docker/containers
                - name: fluent-bit-config
                  configMap:
                      name: fluent-bit-config
            serviceAccountName: fluent-bit
            tolerations:
                - key: node-role.kubernetes.io/master
                  operator: Exists
                  effect: NoSchedule
                - operator: Exists
                  effect: NoExecute
                - operator: Exists
                  effect: NoSchedule
