Vagrant.configure("2") do |config| 
 
    config.vm.define "nfs" do |nfs|
        nfs.vm.box = "ubuntu/bionic64"
        nfs.vm.network "private_network", ip: "192.168.33.41"
	nfs.vm.network "private_network", ip: "10.0.0.41"
        nfs.vm.network "public_network"
        nfs.vm.provider "virtualbox" do |vb|
	  vb.name = "NFS"
          vb.memory = "2024"
          vb.cpus = 2
      end 
    end

end