apiVersion: v1
kind: Service
metadata:
    name: kibana
    namespace: logging
    labels:
        app: kibana
spec:
    type: NodePort
    ports:
        - port: 5601
          targetPort: 5601
          nodePort: 30604
    selector:
        app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kibana
    namespace: logging
    labels:
        app: kibana
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kibana
    template:
        metadata:
            labels:
                app: kibana
        spec:
            containers:
                - name: kibana
                  image: docker.elastic.co/kibana/kibana:7.13.4 #@8.11.1-amd64 #@7.13.4
                  # resources:
                  #     limits:
                  #         memory: '128Mi'
                  #         cpu: '500m'
                  env:
                      - name: ELASTICSEARCH_URL
                        value: http://elasticsearch:9200
                  ports:
                      - containerPort: 5601
