apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: logstash-pvc
    namespace: logging
spec:
    storageClassName: standard
    volumeName: logstash-pv
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: logstash-pv
    namespace: logging
    labels:
        type: local
spec:
    storageClassName: standard
    capacity:
        storage: 3Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: '/data/logstash'
